import 'package:supabase_flutter/supabase_flutter.dart' as supabase;
import '../../core/models/material.dart';
import '../auth/auth_models.dart';
import 'material_row_mapper.dart';

class ScannedPdfOcrResult { const ScannedPdfOcrResult({required this.material, this.errorMessage}); final StudyMaterial material; final String? errorMessage; bool get succeeded => errorMessage == null; }
class ScannedPdfOcrException implements Exception { const ScannedPdfOcrException(this.message); final String message; }
abstract class ScannedPdfOcrRepository { Future<ScannedPdfOcrResult> scan({required AuthUser user, required String materialId}); }
abstract class ScannedPdfOcrDataSource { Future<Object?> invoke(String materialId); }
class SupabaseScannedPdfOcrDataSource implements ScannedPdfOcrDataSource { const SupabaseScannedPdfOcrDataSource(this.client); final supabase.SupabaseClient client; @override Future<Object?> invoke(String id) async => (await client.functions.invoke('extract-scanned-pdf-text', body: {'material_id': id})).data; }
class SupabaseScannedPdfOcrRepository implements ScannedPdfOcrRepository { const SupabaseScannedPdfOcrRepository(this.source); final ScannedPdfOcrDataSource source;
  @override Future<ScannedPdfOcrResult> scan({required AuthUser user, required String materialId}) async { try { final raw = await source.invoke(materialId); if (raw is! Map) throw const ScannedPdfOcrException(_generic); final data = Map<String, dynamic>.from(raw); if (data['material'] is! Map) throw const ScannedPdfOcrException(_generic); final material = mapMaterialRow(Map<String, dynamic>.from(data['material'] as Map)); final error = data['error']; final message = error is Map ? _safe(Map<String, dynamic>.from(error)['message']) : null; return ScannedPdfOcrResult(material: material, errorMessage: data['ok'] == true ? null : message ?? _generic); } on ScannedPdfOcrException { rethrow; } catch (_) { throw const ScannedPdfOcrException(_generic); } }
  static const _generic = 'Could not scan this PDF. Try again.'; String? _safe(Object? value) => value is String && const {'This version can scan PDFs up to 10 pages. Split the PDF and upload a smaller file.','No readable text was found in the scanned PDF.','Could not read the uploaded PDF.','The uploaded file is not a valid PDF.','Could not scan this PDF. Try again.'}.contains(value) ? value : null;
}
class EmptyScannedPdfOcrRepository implements ScannedPdfOcrRepository { const EmptyScannedPdfOcrRepository(); @override Future<ScannedPdfOcrResult> scan({required AuthUser user, required String materialId}) => throw const ScannedPdfOcrException('Scanned PDF OCR is not configured.'); }
class MockScannedPdfOcrRepository implements ScannedPdfOcrRepository { const MockScannedPdfOcrRepository(); @override Future<ScannedPdfOcrResult> scan({required AuthUser user, required String materialId}) async => ScannedPdfOcrResult(material: StudyMaterial(id: materialId, subjectId: 'biology', title: 'Mock scanned PDF', kind: MaterialKind.pdf, content: '--- Page 1 ---\n\nDeterministic scanned PDF OCR text with enough useful study content for summaries, flashcards, quizzes, and study sessions.', createdLabel: 'Just now', sourceKind: MaterialSourceKind.upload, storageBucket: 'study-materials', storagePath: '${user.id}/$materialId/mock.pdf', mimeType: 'application/pdf', fileSizeBytes: 1024, processingStatus: MaterialProcessingStatus.ready, scannedPdfOcr: ScannedPdfOcrMetadata(extractedAt: DateTime.utc(2026), processedPages: const [1], totalPages: 1, characterCount: 128, extractionVersion: 'scanned-pdf-ocr-v1', provider: 'mock', model: 'mock'))); }
